modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="fuck_subanomalyone"
version="1.0.0"
displayName="Fuck SubAnomalyOne"
displayURL="https://modrinth.com/user/blade_fyr"
logoFile="logo.png"
credits="made by blade_fyr"
authors="blade_fyr"
description="Tired of SubAnomalyOne? This mod removes him out of the game!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fuck_subanomalyone]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fuck_subanomalyone]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration